// src/components/ChessCoordinates.tsx
import type { Accessor, Component, JSX } from "solid-js";
import { For } from "solid-js";

export type ChessCoordinatesType = "files" | "ranks";

export type ChessCoordinatesProps = {
  type: ChessCoordinatesType;
  gridArea: string;
  flip: Accessor<boolean>;
};

export const ChessCoordinates: Component<ChessCoordinatesProps> = (props: ChessCoordinatesProps): JSX.Element => {
  return (
    <div
      style={{ "grid-area": props.gridArea }}
      class="grid"
      classList={{
        "grid-rows-1 grid-cols-8": props.type === "files",
        "grid-rows-8 grid-cols-1": props.type === "ranks",
      }}
    >
      <For each={coordinates[props.type]}>
        {(label: number | string): JSX.Element => (
          <div
            class="m-auto flex size-5 items-center justify-center text-sm font-semibold text-stone-50/50 select-none"
            classList={{ "rotate-180": props.flip() }}
          >
            {label}
          </div>
        )}
      </For>
    </div>
  );
};

export const files: Readonly<string[]> = Object.freeze(["a", "b", "c", "d", "e", "f", "g", "h"]);
export const ranks: Readonly<number[]> = Object.freeze([8, 7, 6, 5, 4, 3, 2, 1]);
export const coordinates: Readonly<Record<ChessCoordinatesType, Readonly<(number | string)[]>>> = Object.freeze({ files, ranks });

// packages/angular/src/app/components/chess-coordinates.component.ts
import { NgClass } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, ViewEncapsulation } from "@angular/core";

export type ChessCoordinatesType = "files" | "ranks";

export const FILES: readonly string[] = Object.freeze(["a", "b", "c", "d", "e", "f", "g", "h"]);
export const RANKS: readonly number[] = Object.freeze([8, 7, 6, 5, 4, 3, 2, 1]);
export const COORDINATES: Readonly<Record<ChessCoordinatesType, readonly (number | string)[]>> = Object.freeze({
  files: FILES,
  ranks: RANKS,
});

@Component({
  selector: "chess-coordinates",
  template: `
    <div
      [style.grid-area]="gridArea()"
      class="grid"
      [ngClass]="{
        'grid-cols-8 grid-rows-1': type() === 'files',
        'grid-cols-1 grid-rows-8': type() === 'ranks',
      }"
    >
      @for (label of coordinates; track label) {
        <div
          class="m-auto flex size-5 items-center justify-center text-sm font-semibold text-stone-50/50 select-none"
          [ngClass]="{ 'rotate-180': flip() }"
        >
          {{ label }}
        </div>
      }
    </div>
  `,
  host: { class: "contents" },
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [NgClass],
})
export class ChessCoordinatesComponent {
  type = input.required<ChessCoordinatesType>();
  gridArea = input.required<string>();
  flip = input(false);

  get coordinates(): readonly (number | string)[] {
    return COORDINATES[this.type()];
  }
}
