// src/components/ChessPiece.tsx
import type { Color, PieceSymbol } from "chess.js";
import type { Accessor, Component, JSX } from "solid-js";

export type ChessPieceType = {
  id?: string;
  color: Color;
  type: PieceSymbol;
};

export type ChessPieceProps = {
  piece: Accessor<ChessPieceType>;
  selected?: Accessor<boolean>;
  flip?: Accessor<boolean>;
};

export const ChessPiece: Component<ChessPieceProps> = ({ piece, selected, flip }: ChessPieceProps): JSX.Element => {
  const { id, color, type } = piece();
  return (
    <svg
      id={id}
      style={{ "view-transition-name": id }}
      class="size-full drop-shadow-xs transition-all duration-200"
      classList={{
        "fill-zinc-300 drop-shadow-zinc-900": color === "w",
        "fill-zinc-900 drop-shadow-zinc-300": color === "b",
        "scale-125": selected?.(),
        "rotate-180": flip?.(),
      }}
      aria-label={`${colorNames[color]} ${pieceNames[type]}`}
      role="img"
    >
      <use href={`./chess.svg#${type}`} />
    </svg>
  );
};

const colorNames: Readonly<Record<Color, string>> = Object.freeze({
  w: "White",
  b: "Black",
});

const pieceNames: Readonly<Record<PieceSymbol, string>> = Object.freeze({
  p: "Pawn",
  n: "Knight",
  b: "Bishop",
  r: "Rook",
  q: "Queen",
  k: "King",
});

// packages/angular/src/app/components/chess-piece.component.ts
import { NgClass } from "@angular/common";
import { ChangeDetectionStrategy, Component, input, ViewEncapsulation } from "@angular/core";

import { COLOR_NAMES, PIECE_NAMES, type ChessPieceType } from "@chess/shared";

@Component({
  selector: "chess-piece",
  template: `
    <svg
      [id]="piece().id"
      [style.view-transition-name]="piece().id"
      class="size-full drop-shadow-xs transition-all duration-200"
      [ngClass]="{
        'fill-zinc-300 drop-shadow-zinc-900': piece().color === 'w',
        'fill-zinc-900 drop-shadow-zinc-300': piece().color === 'b',
        'scale-125': selected(),
        'rotate-180': flip(),
      }"
      [attr.aria-label]="COLOR_NAMES[piece().color] + ' ' + PIECE_NAMES[piece().type]"
      role="img"
    >
      <use [attr.href]="'./chess.svg#' + piece().type" />
    </svg>
  `,
  host: { class: "contents" },
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [NgClass],
})
export class ChessPieceComponent {
  piece = input.required<ChessPieceType>();
  selected = input(false);
  flip = input(false);

  protected readonly COLOR_NAMES = COLOR_NAMES;
  protected readonly PIECE_NAMES = PIECE_NAMES;
}
