// src/components/ChessSquare.tsx
import type { Square } from "chess.js";
import type { Accessor, Component, JSX } from "solid-js";
import { createEffect, Show } from "solid-js";

import { useChess } from "~/contexts/ChessContext";
import { getAdjacentSquare } from "~/utils/keyboard-navigation";

import type { ChessPieceType } from "./ChessPiece";
import { ChessPiece } from "./ChessPiece";

export type ChessSquareColor = "light" | "dark" | null;
export type ChessSquareInCheck = "check" | "checkmate" | null;

export type ChessSquareProps = {
  square: Square;
  color: ChessSquareColor;
};

export const ChessSquare: Component<ChessSquareProps> = ({ square, color }: ChessSquareProps): JSX.Element => {
  const { player, flip, board, selectedSquare, focusedSquare, setFocusedSquare, validMoves, lastMove, onSquareClick, isCheck, isCheckmate, turn } =
    useChess();

  let squareRef: HTMLDivElement | undefined;

  const piece = () => board()[square];
  const isSelected = () => selectedSquare() === square;
  const isFocused = () => focusedSquare() === square;
  const isValidMove = () => validMoves().includes(square);
  const isLastMove = () => lastMove()?.from === square || lastMove()?.to === square;
  const tabIndex = () => (isFocused() ? 0 : -1);
  const isInCheck = (): ChessSquareInCheck => {
    if (piece()?.type !== "k" || piece()?.color !== turn()) return null;
    if (isCheckmate()) return "checkmate";
    if (isCheck()) return "check";
    return null;
  };

  // Auto-focus when focused square changes
  createEffect(() => {
    if (isFocused() && squareRef) {
      squareRef.focus();
    }
  });

  const onSquarePress = (event: KeyboardEvent) => {
    // Enter/Space: Select piece or make move
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      onSquareClick(square);
      return;
    }

    // Arrow keys: Navigate between squares
    const arrowMap: Record<string, "up" | "down" | "left" | "right" | undefined> = {
      ArrowUp: "up",
      ArrowDown: "down",
      ArrowLeft: "left",
      ArrowRight: "right",
    };

    const direction = arrowMap[event.key];
    if (!direction) return;

    event.preventDefault();
    const nextSquare = getAdjacentSquare(square, direction, flip());
    if (nextSquare) {
      setFocusedSquare(nextSquare);
    }
  };

  const getEnhancedAriaLabel = (square: Square, piece: ChessPieceType | null | undefined, isSelected: boolean, isValidMove: boolean): string => {
    const parts = [square.toUpperCase()];

    if (piece) {
      const colorName = piece.color === "w" ? "White" : "Black";
      const pieceNames: Record<string, string> = {
        p: "Pawn",
        n: "Knight",
        b: "Bishop",
        r: "Rook",
        q: "Queen",
        k: "King",
      };
      const pieceName = pieceNames[piece.type] || piece.type;
      parts.push(`${colorName} ${pieceName}`);
    } else {
      parts.push(isValidMove ? "valid move" : "empty");
    }

    if (isSelected) parts.push("selected");
    if (isValidMove && piece) parts.push("capturable");

    return parts.join(", ");
  };

  return (
    <div
      ref={squareRef}
      id={square}
      tabIndex={tabIndex()}
      role="gridcell"
      aria-selected={isSelected()}
      style={{ padding: "15%" }}
      class="relative inline-flex aspect-square items-center justify-center select-none hover:opacity-85 focus:outline-none focus-visible:z-10 focus-visible:ring-4 focus-visible:ring-blue-400 focus-visible:ring-offset-2 focus-visible:ring-offset-stone-800"
      classList={{
        "bg-red-200/25": isInCheck() !== null,
        "animate-pulse": isInCheck() === "check",
        "bg-amber-200/25": !isInCheck() && isLastMove(),
        "bg-stone-500": !isInCheck() && !isLastMove() && color === "light",
        "bg-stone-600": !isInCheck() && !isLastMove() && color === "dark",
        "cursor-pointer": isValidMove() || piece()?.color === player(),
      }}
      aria-label={getEnhancedAriaLabel(square, piece(), isSelected(), isValidMove())}
      onKeyDown={(event: KeyboardEvent) => onSquarePress(event)}
      onClick={() => onSquareClick(square)}
    >
      <Show when={piece()}>
        {(piece: Accessor<ChessPieceType>): JSX.Element => (
          <div class="flex size-full items-center justify-center">
            <ChessPiece piece={piece} selected={isSelected as Accessor<boolean>} flip={flip} />
          </div>
        )}
      </Show>
      <Show when={isValidMove() && !piece()}>
        <div class="size-1/5 animate-pulse rounded-full bg-stone-50/50" />
      </Show>
      <Show when={isValidMove() && piece()}>
        <div style={{ inset: "5%" }} class="absolute rounded-full border-4 border-stone-50/50 opacity-50" />
      </Show>
    </div>
  );
};

// packages/angular/src/app/components/chess-square.component.ts
import { NgClass } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, effect, ElementRef, inject, input, viewChild, ViewEncapsulation } from "@angular/core";
import type { Square } from "chess.js";

import type { ChessSquareColor, ChessSquareInCheck } from "../chess.types";
import { ChessService } from "../services/chess.service";
import { getAdjacentSquare } from "../utils/keyboard-navigation";
import { ChessPieceComponent } from "./chess-piece.component";

@Component({
  selector: "chess-square",
  template: `
    <div
      #squareRef
      [id]="square()"
      [tabIndex]="tabIndex()"
      role="gridcell"
      [attr.aria-selected]="isSelected()"
      [style.padding]="'15%'"
      class="relative inline-flex aspect-square items-center justify-center select-none hover:opacity-85 focus:outline-none focus-visible:z-10 focus-visible:ring-4 focus-visible:ring-blue-400 focus-visible:ring-offset-2 focus-visible:ring-offset-stone-800"
      [ngClass]="{
        'bg-red-200/25': isInCheck() !== null,
        'animate-pulse': isInCheck() === 'check',
        'bg-amber-200/25': !isInCheck() && isLastMove(),
        'bg-stone-500': !isInCheck() && !isLastMove() && color() === 'light',
        'bg-stone-600': !isInCheck() && !isLastMove() && color() === 'dark',
        'cursor-pointer': isValidMove() || piece()?.color === chess.player(),
      }"
      [attr.aria-label]="ariaLabel()"
      (keydown)="onSquarePress($event)"
      (click)="chess.onSquareClick(square())"
    >
      @if (piece(); as p) {
        <div class="flex size-full items-center justify-center">
          <chess-piece [piece]="p" [selected]="isSelected()" [flip]="chess.flip()" />
        </div>
      }
      @if (isValidMove() && !piece()) {
        <div class="size-1/5 animate-pulse rounded-full bg-stone-50/50"></div>
      }
      @if (isValidMove() && piece()) {
        <div style="inset: 5%" class="absolute rounded-full border-4 border-stone-50/50 opacity-50"></div>
      }
    </div>
  `,
  host: { class: "contents" },
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [NgClass, ChessPieceComponent],
})
export class ChessSquareComponent {
  protected chess = inject(ChessService);

  square = input.required<Square>();
  color = input.required<ChessSquareColor>();

  private squareRef = viewChild<ElementRef<HTMLDivElement>>("squareRef");

  piece = computed(() => this.chess.board()[this.square()]);
  isSelected = computed(() => this.chess.selectedSquare() === this.square());
  isFocused = computed(() => this.chess.focusedSquare() === this.square());
  isValidMove = computed(() => this.chess.validMoves().includes(this.square()));
  isLastMove = computed(() => {
    const lastMove = this.chess.lastMove();
    return lastMove?.from === this.square() || lastMove?.to === this.square();
  });
  tabIndex = computed(() => (this.isFocused() ? 0 : -1));

  isInCheck = computed((): ChessSquareInCheck => {
    const piece = this.piece();
    if (piece?.type !== "k" || piece?.color !== this.chess.turn()) return null;
    if (this.chess.isCheckmate()) return "checkmate";
    if (this.chess.isCheck()) return "check";
    return null;
  });

  ariaLabel = computed(() => {
    const square = this.square();
    const piece = this.piece();
    const isSelected = this.isSelected();
    const isValidMove = this.isValidMove();

    const parts = [square.toUpperCase()];

    if (piece) {
      const colorName = piece.color === "w" ? "White" : "Black";
      const pieceNames: Record<string, string> = {
        p: "Pawn",
        n: "Knight",
        b: "Bishop",
        r: "Rook",
        q: "Queen",
        k: "King",
      };
      const pieceName = pieceNames[piece.type] || piece.type;
      parts.push(`${colorName} ${pieceName}`);
    } else {
      parts.push(isValidMove ? "valid move" : "empty");
    }

    if (isSelected) parts.push("selected");
    if (isValidMove && piece) parts.push("capturable");

    return parts.join(", ");
  });

  constructor() {
    effect(() => {
      if (this.isFocused()) {
        const ref = this.squareRef();
        if (ref) {
          ref.nativeElement.focus();
        }
      }
    });
  }

  onSquarePress(event: KeyboardEvent): void {
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      this.chess.onSquareClick(this.square());
      return;
    }

    const arrowMap: Record<string, "up" | "down" | "left" | "right" | undefined> = {
      ArrowUp: "up",
      ArrowDown: "down",
      ArrowLeft: "left",
      ArrowRight: "right",
    };

    const direction = arrowMap[event.key];
    if (!direction) return;

    event.preventDefault();
    const nextSquare = getAdjacentSquare(this.square(), direction, this.chess.flip());
    if (nextSquare) {
      this.chess.focusedSquare.set(nextSquare);
    }
  }
}
