// src/components/ChessEnd/ChessEnd.tsx
import type { Accessor, Component, JSX } from "solid-js";
import { Show, createEffect, createMemo } from "solid-js";

import type { Color } from "~/chess";
import { useChess } from "~/contexts/ChessContext";
import { falsy } from "~/utils/constants";

import { ChessPiece, blackKing, colorNames, whiteKing } from "../ChessPiece/ChessPiece";
import type { ChessPieceType } from "../ChessPiece/ChessPiece";

type GameResult = {
  message: string;
  player: Color | null;
};

export const ChessEnd: Component = (): JSX.Element => {
  const { isGameOver, isCheckmate, isStalemate, isThreefoldRepetition, isInsufficientMaterial, turn, player, resetGame } = useChess();

  const result = createMemo<GameResult>(() => {
    if (isCheckmate()) {
      const isPlayerWin = turn() !== player();
      const winner = isPlayerWin ? player() : turn();
      return { message: `Checkmate! ${colorNames[winner]} Wins!`, player: winner };
    }
    if (isStalemate()) return { message: "Stalemate!", player: null };
    if (isThreefoldRepetition()) return { message: "Draw by Threefold Repetition!", player: null };
    if (isInsufficientMaterial()) return { message: "Draw by Insufficient Material!", player: null };
    return { message: "Draw!", player: null };
  });

  const resultPlayer = createMemo<Accessor<ChessPieceType>>(() => {
    switch (result().player) {
      case "w":
        return whiteKing;
      case "b":
        return blackKing;
      default:
        return player() === "w" ? whiteKing : blackKing;
    }
  });

  let playAgainRef: HTMLButtonElement | undefined;

  createEffect(() => {
    if (isGameOver() && playAgainRef) playAgainRef.focus();
  });

  return (
    <Show when={isGameOver()}>
      <div class="fixed inset-0 z-10 flex items-center justify-center bg-black/50 backdrop-blur-xs">
        <div
          class="flex flex-col items-center gap-3 rounded-lg bg-stone-800 p-4 pt-3 shadow-sm shadow-stone-600"
          role="dialog"
          aria-modal="true"
          aria-labelledby="chess-end-title"
        >
          <h2 id="chess-end-title" class="text-base/normal font-bold text-white">
            {result().message}
          </h2>
          <div class="size-16">
            <ChessPiece piece={resultPlayer()} selected={falsy} flip={falsy} />
          </div>
          <button
            ref={(el) => (playAgainRef = el)}
            class="mt-1 cursor-pointer rounded-lg px-3 py-1 text-base font-bold transition-all"
            classList={{
              "bg-zinc-300 text-zinc-900 hover:bg-zinc-400": player() === "w",
              "bg-zinc-900 text-zinc-300 hover:bg-zinc-800": player() === "b",
            }}
            onClick={resetGame}
          >
            Play Again
          </button>
        </div>
      </div>
    </Show>
  );
};

// packages/angular/src/app/components/chess-end.component.ts
import { NgClass } from "@angular/common";
import { ChangeDetectionStrategy, Component, computed, inject, ViewEncapsulation } from "@angular/core";

import type { ChessPieceType, GameResult } from "../chess.types";
import { COLOR_NAMES } from "../chess.types";
import { ChessService } from "../services/chess.service";
import { ChessPieceComponent } from "./chess-piece.component";

const WHITE_KING: ChessPieceType = { id: "white-king", color: "w", type: "k" };
const BLACK_KING: ChessPieceType = { id: "black-king", color: "b", type: "k" };

@Component({
  selector: "chess-end",
  template: `
    @if (chess.isGameOver()) {
      <div class="fixed inset-0 z-10 flex items-center justify-center bg-black/50 backdrop-blur-xs">
        <div class="flex flex-col items-center gap-3 rounded-lg bg-stone-800 p-4 pt-3 shadow-sm shadow-stone-600">
          <h2 class="text-base/normal font-bold text-white">{{ resultMessage() }}</h2>
          <div class="size-16">
            <chess-piece [piece]="resultPlayer()" [selected]="false" [flip]="false" />
          </div>
          <button
            class="mt-1 cursor-pointer rounded-lg px-3 py-1 text-base font-bold transition-all"
            [ngClass]="{
              'bg-zinc-300 text-zinc-900 hover:bg-zinc-400': chess.player() === 'w',
              'bg-zinc-900 text-zinc-300 hover:bg-zinc-800': chess.player() === 'b',
            }"
            aria-label="Play Again"
            (click)="chess.resetGame()"
          >
            Play Again
          </button>
        </div>
      </div>
    }
  `,
  host: { class: "contents" },
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [NgClass, ChessPieceComponent],
})
export class ChessEndComponent {
  protected chess = inject(ChessService);

  result = computed<GameResult>(() => {
    if (this.chess.isCheckmate()) {
      const isPlayerWin = this.chess.turn() !== this.chess.player();
      return {
        type: isPlayerWin ? "win" : "lose",
        player: isPlayerWin ? this.chess.player() : this.chess.turn(),
      };
    }
    if (this.chess.isStalemate()) {
      return { type: "stalemate", player: null };
    }
    if (this.chess.isDraw() || this.chess.isThreefoldRepetition() || this.chess.isInsufficientMaterial()) {
      return { type: "draw", player: null };
    }
    return { type: "draw", player: null };
  });

  resultMessage = computed(() => {
    const result = this.result();
    switch (result.type) {
      case "win":
      case "lose":
        return `Checkmate! ${COLOR_NAMES[result.player!]} Wins!`;
      case "stalemate":
        return "Stalemate!";
      case "draw":
        if (this.chess.isThreefoldRepetition()) return "Draw by Threefold Repetition!";
        if (this.chess.isInsufficientMaterial()) return "Draw by Insufficient Material!";
        return "Draw!";
    }
  });

  resultPlayer = computed<ChessPieceType>(() => {
    const result = this.result();
    switch (result.player) {
      case "w":
        return WHITE_KING;
      case "b":
        return BLACK_KING;
      default:
        return this.chess.player() === "w" ? WHITE_KING : BLACK_KING;
    }
  });
}
